### ISSUE TITLE
Strange error with upload script

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-build-setup-feedstock#60]
```python
Fetching package metadata .....
Traceback (most recent call last):
  File "C:\Miniconda\Scripts\upload_or_check_non_existence.py", line 140, in <module>
    main()
  File "C:\Miniconda\Scripts\upload_or_check_non_existence.py", line 124, in main
    upload(cli, meta, owner, channel)
  File "C:\Miniconda\Scripts\upload_or_check_non_existence.py", line 62, in upload
    env=os.environ)
  File "C:\Miniconda\lib\subprocess.py", line 181, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Miniconda\lib\subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Miniconda\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Miniconda\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
TypeError: environment can only contain strings
Command exited with code 1
```

ref: https://ci.appveyor.com/project/conda-forge/opencv-feedstock/build/1.0.141/job/5b2ai3osb0rbk4w7#L4955

**Comment by jakirkham** [comment]
FWIW these seem to be the [lines]( https://github.com/conda-forge/conda-forge-build-setup-feedstock/blob/559ed563e6b1870e090bd8138155101b2f7c1793/recipe/upload_or_check_non_existence.py#L58-L62 ) where the problem occurs.

**Comment by jakirkham** [comment]
After pinning `conda-build` to 2.1.4, it appears this issue has gone away. As such, this appears to be an issue with `conda-build`. Am closing this issue to consolidate the discussion in issue ( https://github.com/conda/conda-build/issues/1853 ).
